name: Create Tag, Zip Folder, and Release

on:
  push:
    branches:
      - SQLite-Implementation-V2
  workflow_dispatch: # This lets you manually trigger the action

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Get current date
      id: current_time
      run: echo "TIMESTAMP=$(date +'%d_%m_%Y')" >> $GITHUB_ENV

    - name: Zip published folder
      run: zip -r Release.zip published/

    - name: Create Tag
      run: |
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"
        git tag release-${{ github.sha }}_${{ env.TIMESTAMP }}
        git push origin release-${{ github.sha }}_${{ env.TIMESTAMP }}
      env:
        GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
      with:
        tag_name: release-${{ github.sha }}_${{ env.TIMESTAMP }}
        release_name: Release for ${{ env.TIMESTAMP }}
        draft: false
        prerelease: false

    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./Release.zip
        asset_name: Release.zip
        asset_content_type: application/zip
