name: Create Tag and Release

on:
  push:
    branches:
      - SQLite-Implementation-V2  # Adjust this if needed

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Get current date
      id: current_time
      run: echo "TIMESTAMP=$(date +'%d_%m_%Y')" >> $GITHUB_ENV

    - name: Create Tag
      run: |
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"
        git tag release-${{ github.sha }}_${{ env.TIMESTAMP }}
        git push origin release-${{ github.sha }}_${{ env.TIMESTAMP }}

    - name: Create Release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: release-${{ github.sha }}_${{ env.TIMESTAMP }}
        release_name: Release for ${{ env.TIMESTAMP }}
        draft: false
        prerelease: false
